language: python
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database django_ttdb;' -U postgres
python:
  - "2.7"
  - "3.4"
env:
  - DJANGO_VERSION=1.8.17
  - DJANGO_VERSION=1.9.12
  - DJANGO_VERSION=1.10.4
install:
  - pip install -e .
  - pip install Django==$DJANGO_VERSION psycopg2
script: make test
